import type { IVeThemeVars } from '~/utils/css/vanillaExtract.types';
import type { IRuntimeThemeTokens, ITheme } from '../theme.types';

// You should always explicitly set values unit (ie. `px` or `rem`). Otherwise,
// CSS calc() may not work as expected.

export const getDefaultTheme = (
  runtimeTokens?: IVeThemeVars<IRuntimeThemeTokens>,
): ITheme => {
  const DEFAULT_FONT_FAMILY =
    '-apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Helvetica, Arial, sans-serif, Apple Color Emoji, Segoe UI Emoji';

  const defaultTheme: ITheme = {
    name: 'Material Design 3',
    seed: {
      color: '#6750a4',
      schemeVariant: 'vibrant2',
      contrast: 0,
    },
    windowSizeClasses: {
      compact: '600px',
      medium: '960px',
      expanded: '1280px',
      large: '1440px',
      extraLarge: undefined,
    },
    tokens: {
      scale: '1',
      colorScheme: {
        light: {
          primary: '#6750A4',
          onPrimary: '#FFFFFF',
          primaryContainer: '#EADDFF',
          onPrimaryContainer: '#4F378B',
          secondary: '#625B71',
          onSecondary: '#FFFFFF',
          secondaryContainer: '#E8DEF8',
          onSecondaryContainer: '#4A4458',
          tertiary: '#7D5260',
          onTertiary: '#FFFFFF',
          tertiaryContainer: '#FFD8E4',
          onTertiaryContainer: '#633B48',
          error: '#B3261E',
          onError: '#FFFFFF',
          errorContainer: '#F9DEDC',
          onErrorContainer: '#8C1D18',
          surface: '#FEF7FF',
          onSurface: '#1D1B20',
          surfaceVariant: '#E7E0EC',
          onSurfaceVariant: '#49454F',
          surfaceContainerHighest: '#E6E0E9',
          surfaceContainerHigh: '#ECE6F0',
          surfaceContainer: '#F3EDF7',
          surfaceContainerLow: '#F7F2FA',
          surfaceContainerLowest: '#FFFFFF',
          inverseSurface: '#322F35',
          inverseOnSurface: '#F5EFF7',
          outline: '#79747E',
          outlineVariant: '#CAC4D0',
          primaryFixed: '#EADDFF',
          onPrimaryFixed: '#21005D',
          primaryFixedDim: '#D0BCFF',
          onPrimaryFixedVariant: '#4F378B',
          inversePrimary: '#D0BCFF',
          secondaryFixed: '#E8DEF8',
          onSecondaryFixed: '#1D192B',
          onSecondaryFixedVariant: '#4A4458',
          secondaryFixedDim: '#CCC2DC',
          tertiaryFixed: '#FFD8E4',
          onTertiaryFixed: '#31111D',
          onTertiaryFixedVariant: '#633B48',
          tertiaryFixedDim: '#EFB8C8',
          surfaceBright: '#FEF7FF',
          surfaceDim: '#DED8E1',
          scrim: '#000000',
          shadow: '#000000',
        },
        dark: {
          primary: '#D0BCFF',
          onPrimary: '#381E72',
          primaryContainer: '#4F378B',
          onPrimaryContainer: '#EADDFF',
          secondary: '#CCC2DC',
          onSecondary: '#332D41',
          secondaryContainer: '#4A4458',
          onSecondaryContainer: '#E8DEF8',
          tertiary: '#EFB8C8',
          onTertiary: '#492532',
          tertiaryContainer: '#633B48',
          onTertiaryContainer: '#FFD8E4',
          error: '#F2B8B5',
          onError: '#601410',
          errorContainer: '#8C1D18',
          onErrorContainer: '#F9DEDC',
          surface: '#141218',
          onSurface: '#E6E0E9',
          surfaceVariant: '#49454F',
          onSurfaceVariant: '#CAC4D0',
          surfaceContainerHighest: '#36343B',
          surfaceContainerHigh: '#2B2930',
          surfaceContainer: '#211F26',
          surfaceContainerLow: '#1D1B20',
          surfaceContainerLowest: '#0F0D13',
          inverseSurface: '#E6E0E9',
          inverseOnSurface: '#322F35',
          outline: '#938F99',
          outlineVariant: '#49454F',
          primaryFixed: '#EADDFF',
          onPrimaryFixed: '#21005D',
          primaryFixedDim: '#D0BCFF',
          onPrimaryFixedVariant: '#4F378B',
          inversePrimary: '#6750A4',
          secondaryFixed: '#E8DEF8',
          onSecondaryFixed: '#4A4458',
          onSecondaryFixedVariant: '#4A4458',
          secondaryFixedDim: '#CCC2DC',
          tertiaryFixed: '#FFD8E4',
          onTertiaryFixed: '#31111D',
          onTertiaryFixedVariant: '#633B48',
          tertiaryFixedDim: '#EFB8C8',
          surfaceBright: '#3B383E',
          surfaceDim: '#3B383E',
          scrim: '#000000',
          shadow: '#000000',
        },
      },
      typeFace: {
        brand: DEFAULT_FONT_FAMILY,
        plain: DEFAULT_FONT_FAMILY,
        weight: {
          regular: '400',
          medium: '500',
          bold: '700',
        },
      },
      typeScale: {
        display: {
          lg: {
            family: runtimeTokens?.typeFace.brand ?? '',
            lineHeight: '4rem',
            size: '3.5625rem',
            letterSpacing: '-0.015625rem',
            weight: runtimeTokens?.typeFace.weight.regular ?? '',
            weightProminent: runtimeTokens?.typeFace.weight.medium ?? '',
          },
          md: {
            family: runtimeTokens?.typeFace.brand ?? '',
            lineHeight: '3.25rem',
            size: '2.8125rem',
            letterSpacing: '0rem',
            weight: runtimeTokens?.typeFace.weight.regular ?? '',
            weightProminent: runtimeTokens?.typeFace.weight.medium ?? '',
          },
          sm: {
            family: runtimeTokens?.typeFace.brand ?? '',
            lineHeight: '2.75rem',
            size: '2.25rem',
            letterSpacing: '0rem',
            weight: runtimeTokens?.typeFace.weight.regular ?? '',
            weightProminent: runtimeTokens?.typeFace.weight.medium ?? '',
          },
        },
        headline: {
          lg: {
            family: runtimeTokens?.typeFace.brand ?? '',
            lineHeight: '2.5rem',
            size: '2rem',
            letterSpacing: '0rem',
            weight: runtimeTokens?.typeFace.weight.regular ?? '',
            weightProminent: runtimeTokens?.typeFace.weight.medium ?? '',
          },
          md: {
            family: runtimeTokens?.typeFace.brand ?? '',
            lineHeight: '2.25rem',
            size: '1.75rem',
            letterSpacing: '0rem',
            weight: runtimeTokens?.typeFace.weight.regular ?? '',
            weightProminent: runtimeTokens?.typeFace.weight.medium ?? '',
          },
          sm: {
            family: runtimeTokens?.typeFace.brand ?? '',
            lineHeight: '2rem',
            size: '1.5rem',
            letterSpacing: '0rem',
            weight: runtimeTokens?.typeFace.weight.regular ?? '',
            weightProminent: runtimeTokens?.typeFace.weight.medium ?? '',
          },
        },
        title: {
          lg: {
            family: runtimeTokens?.typeFace.brand ?? '',
            lineHeight: '1.75rem',
            size: '1.375rem',
            letterSpacing: '0rem',
            weight: runtimeTokens?.typeFace.weight.regular ?? '',
            weightProminent: runtimeTokens?.typeFace.weight.medium ?? '',
          },
          md: {
            family: runtimeTokens?.typeFace.plain ?? '',
            lineHeight: '1.5rem',
            size: '1rem',
            letterSpacing: '0.009375rem',
            weight: runtimeTokens?.typeFace.weight.medium ?? '',
            weightProminent: runtimeTokens?.typeFace.weight.bold ?? '',
          },
          sm: {
            family: runtimeTokens?.typeFace.plain ?? '',
            lineHeight: '1.25rem',
            size: '0.875rem',
            letterSpacing: '0.00625rem',
            weight: runtimeTokens?.typeFace.weight.medium ?? '',
            weightProminent: runtimeTokens?.typeFace.weight.bold ?? '',
          },
        },
        body: {
          lg: {
            family: runtimeTokens?.typeFace.plain ?? '',
            lineHeight: '1.5rem',
            size: '1rem',
            letterSpacing: '0.03125rem',
            weight: runtimeTokens?.typeFace.weight.regular ?? '',
            weightProminent: runtimeTokens?.typeFace.weight.medium ?? '',
          },
          md: {
            family: runtimeTokens?.typeFace.plain ?? '',
            lineHeight: '1.25rem',
            size: '0.875rem',
            letterSpacing: '0.015625rem',
            weight: runtimeTokens?.typeFace.weight.regular ?? '',
            weightProminent: runtimeTokens?.typeFace.weight.medium ?? '',
          },
          sm: {
            family: runtimeTokens?.typeFace.plain ?? '',
            lineHeight: '1rem',
            size: '0.75rem',
            letterSpacing: '0.025rem',
            weight: runtimeTokens?.typeFace.weight.regular ?? '',
            weightProminent: runtimeTokens?.typeFace.weight.medium ?? '',
          },
        },
        label: {
          lg: {
            family: runtimeTokens?.typeFace.plain ?? '',
            lineHeight: '1.25rem',
            size: '0.875rem',
            letterSpacing: '0.00625rem',
            weight: runtimeTokens?.typeFace.weight.medium ?? '',
            weightProminent: runtimeTokens?.typeFace.weight.bold ?? '',
          },
          md: {
            family: runtimeTokens?.typeFace.plain ?? '',
            lineHeight: '1rem',
            size: '0.75rem',
            letterSpacing: '0.03125rem',
            weight: runtimeTokens?.typeFace.weight.medium ?? '',
            weightProminent: runtimeTokens?.typeFace.weight.bold ?? '',
          },
          sm: {
            family: runtimeTokens?.typeFace.plain ?? '',
            lineHeight: '1rem',
            size: '0.6875rem',
            letterSpacing: '0.03125rem',
            weight: runtimeTokens?.typeFace.weight.regular ?? '',
            weightProminent: runtimeTokens?.typeFace.weight.bold ?? '',
          },
        },
      },
      density: {
        scale: '0',
        interval: '4px',
        minTargetSize: '48px',
      },
      motion: {
        easing: {
          emphasized: {
            accelerate: 'cubic-bezier(0.3, 0, 0.8, 0.15)',
            decelerate: 'cubic-bezier(0.05, 0.7, 0.1, 1)',
          },
          standard: {
            normal: 'cubic-bezier(0.2, 0, 0, 1)',
            accelerate: 'cubic-bezier(0.3, 0, 1, 1)',
            decelerate: 'cubic-bezier(0, 0, 0, 1)',
          },
          linear: 'cubic-bezier(0, 0, 1, 1)',
        },
        duration: {
          short1: '50ms',
          short2: '100ms',
          short3: '150ms',
          short4: '200ms',
          medium1: '250ms',
          medium2: '300ms',
          medium3: '350ms',
          medium4: '400ms',
          long1: '450ms',
          long2: '500ms',
          long3: '550ms',
          long4: '600ms',
          extraLong1: '700ms',
          extraLong2: '800ms',
          extraLong3: '900ms',
          extraLong4: '1000ms',
        },
      },
      shape: {
        corner: {
          none: '0px',
          xs: '6px',
          sm: '8px',
          md: '12px',
          lg: '16px',
          xl: '28px',
          full: '999px',
          circle: '999px',
        },
      },
      outline: {
        width: {
          none: '0px',
          xs: '1px',
          sm: '2px',
          md: '3px',
          lg: '6px',
          xl: '8px',
        },
      },
      spacing: {
        gridSize: '4px',
      },
      state: {
        stateLayerOpacity: {
          focused: '0.1',
          hovered: '0.08',
          pressed: '0.12',
          dragged: '0.16',
        },
        containerOpacity: {
          disabled: '0.12',
        },
        opacity: {
          disabled: '0.38',
        },
        outlineOpacity: {
          disabled: '0.12',
        },
      },
      zIndex: {
        app: '100',
        modal: '200',
        popover: '300',
        overlay: '400',
        max: '9999',
      },
      elevation: {
        transitionDuration: runtimeTokens?.motion.duration.medium2 ?? '',
        transitionTimingFunction:
          runtimeTokens?.motion.easing.standard.normal ?? '',
        level: {
          0: {
            primary: {
              offsetX: '0px',
              offsetY: '0px',
              blurRadius: '0px',
              spreadRadius: '0px',
              colorOpacityPercentage: '30%',
            },
            secondary: {
              offsetX: '0px',
              offsetY: '0px',
              blurRadius: '0px',
              spreadRadius: '0px',
              colorOpacityPercentage: '15%',
            },
          },
          1: {
            primary: {
              offsetX: '0px',
              offsetY: '1px',
              blurRadius: '2px',
              spreadRadius: '0px',
              colorOpacityPercentage: '30%',
            },
            secondary: {
              offsetX: '0px',
              offsetY: '1px',
              blurRadius: '3px',
              spreadRadius: '1px',
              colorOpacityPercentage: '15%',
            },
          },
          2: {
            primary: {
              offsetX: '0px',
              offsetY: '1px',
              blurRadius: '2px',
              spreadRadius: '0px',
              colorOpacityPercentage: '30%',
            },
            secondary: {
              offsetX: '0px',
              offsetY: '2px',
              blurRadius: '6px',
              spreadRadius: '2px',
              colorOpacityPercentage: '15%',
            },
          },
          3: {
            primary: {
              offsetX: '0px',
              offsetY: '1px',
              blurRadius: '3px',
              spreadRadius: '0px',
              colorOpacityPercentage: '30%',
            },
            secondary: {
              offsetX: '0px',
              offsetY: '4px',
              blurRadius: '8px',
              spreadRadius: '3px',
              colorOpacityPercentage: '15%',
            },
          },
          4: {
            primary: {
              offsetX: '0px',
              offsetY: '2px',
              blurRadius: '3px',
              spreadRadius: '0px',
              colorOpacityPercentage: '30%',
            },
            secondary: {
              offsetX: '0px',
              offsetY: '6px',
              blurRadius: '10px',
              spreadRadius: '4px',
              colorOpacityPercentage: '15%',
            },
          },
          5: {
            primary: {
              offsetX: '0px',
              offsetY: '4px',
              blurRadius: '4px',
              spreadRadius: '0px',
              colorOpacityPercentage: '30%',
            },
            secondary: {
              offsetX: '0px',
              offsetY: '8px',
              blurRadius: '12px',
              spreadRadius: '6px',
              colorOpacityPercentage: '15%',
            },
          },
        },
      },
    },
  };

  return defaultTheme;
};
