export type IElementWithLabelStyleKey =
  | 'host'
  | 'element'
  | 'labelText'
  | 'labelText$error'
  | 'labelText$disabled'
  | 'supportingText'
  | 'supportingText$error'
  | 'supportingText$disabled'
  | 'errorText'
  | 'errorText$disabled';

export type IElementWithLabelStyleVarKey =
  | 'labelTextColor'
  | 'labelTextFont'
  | 'labelTextSize'
  | 'labelTextWeight'
  | 'labelTextLineHeight'
  | 'labelTextLetterSpacing'
  | 'labelTextColor$error'
  | 'labelTextColor$disabled'
  | 'labelTextOpacity$disabled'
  | 'supportingTextColor'
  | 'supportingTextFont'
  | 'supportingTextSize'
  | 'supportingTextWeight'
  | 'supportingTextLineHeight'
  | 'supportingTextLetterSpacing'
  | 'supportingTextColor$error'
  | 'supportingTextColor$disabled'
  | 'supportingTextOpacity$disabled';
