/* 🤖 this file was generated by svg-to-ts */

import type { IIcon } from './lib/my-icons.model';

export type IIconNameSubset<T extends Readonly<Array<IIcon>>> =
  T[number]['name'];

export * from './lib/icon-ArrowDownTray.icon';
export * from './lib/icon-ArrowPath.icon';
export * from './lib/icon-ArrowUpTray.icon';
export * from './lib/icon-Checkmark.icon';
export * from './lib/icon-ChevronDown.icon';
export * from './lib/icon-ChevronRight.icon';
export * from './lib/icon-ChevronUp.icon';
export * from './lib/icon-CopyToCliboard.icon';
export * from './lib/icon-EllipsisHorizontal.icon';
export * from './lib/icon-ExclamationTriangle.icon';
export * from './lib/icon-Eye.icon';
export * from './lib/icon-EyeSlash.icon';
export * from './lib/icon-gripDotsHorizontal.icon';
export * from './lib/icon-gripDotsVertical.icon';
export * from './lib/icon-LeftRight.icon';
export * from './lib/icon-Person.icon';
export * from './lib/icon-Photo.icon';
export * from './lib/icon-TriangleDown.icon';
export * from './lib/icon-TriangleLeft.icon';
export * from './lib/icon-TriangleRight.icon';
export * from './lib/icon-TriangleUp.icon';
export * from './lib/icon-UpDown.icon';
export * from './lib/icon-UpRightAndDownLeftFromCenter.icon';
export * from './lib/icon-WeightHanging.icon';
export * from './lib/icon-XMark.icon';
export * from './lib/my-icons.model';
