/* 🤖 this file was generated by svg-to-ts */

import type { IIcon } from './dist/my-icons.model';

export type IIconNameSubset<T extends Readonly<Array<IIcon>>> =
  T[number]['name'];

export * from './dist/icon-AvatarPlaceholder.icon';
export * from './dist/icon-CheckMark.icon';
export * from './dist/icon-ChevronDown.icon';
export * from './dist/icon-ChevronRight.icon';
export * from './dist/icon-ChevronUp.icon';
export * from './dist/icon-CopyToCliboard.icon';
export * from './dist/icon-EllipsisHorizontal.icon';
export * from './dist/icon-ExclamationTriangle.icon';
export * from './dist/icon-Eye.icon';
export * from './dist/icon-EyeSlash.icon';
export * from './dist/icon-Person.icon';
export * from './dist/icon-Photo.icon';
export * from './dist/icon-TriangleDown.icon';
export * from './dist/icon-TriangleLeft.icon';
export * from './dist/icon-TriangleRight.icon';
export * from './dist/icon-TriangleUp.icon';
export * from './dist/icon-XMark.icon';
export * from './dist/my-icons.model';
