import type { Metadata } from 'next';
import { ColorSchemeScript, sixuiHtmlProps, SixuiProvider } from '@sixui/core';
import { Roboto } from 'next/font/google';

import '@sixui/core/styles.css';

export const metadata: Metadata = {
  title: 'Next.js + React + TS + Sixui',
  description: 'Generated by create next app',
};

const roboto = Roboto({
  weight: ['400', '500', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-roboto',
});

const RootLayout: React.FC<{
  children: React.ReactNode;
}> = ({ children }) => (
  <html lang="en" className={roboto.className} {...sixuiHtmlProps}>
    <head>
      <ColorSchemeScript />
    </head>
    <body>
      <SixuiProvider
        theme={{
          tokens: {
            typeFace: {
              plain: 'Roboto',
              brand: 'Roboto',
            },
          },
        }}
        enableColorSchemePersistence
      >
        {children}
      </SixuiProvider>
    </body>
  </html>
);

export default RootLayout;
