import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';

import './globals.css';
import '@sixui/core/styles.css';

import { sixuiHtmlProps, SixuiProvider } from '@sixui/core';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" {...sixuiHtmlProps}>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <SixuiProvider
          colorSchemeVariant="dark"
          theme={{
            tokens: {
              typeFace: {
                plain: 'Roboto',
                brand: 'Roboto',
              },
            },
          }}
        >
          {children}
        </SixuiProvider>
      </body>
    </html>
  );
}
