import type { IRuntimeThemeTokens } from './theme.types';

export const runtimeThemeTokens: IRuntimeThemeTokens = {
  scale: '',
  colorScheme: {
    primary: '',
    onPrimary: '',
    primaryContainer: '',
    onPrimaryContainer: '',
    secondary: '',
    onSecondary: '',
    secondaryContainer: '',
    onSecondaryContainer: '',
    tertiary: '',
    onTertiary: '',
    tertiaryContainer: '',
    onTertiaryContainer: '',
    error: '',
    onError: '',
    errorContainer: '',
    onErrorContainer: '',
    surface: '',
    onSurface: '',
    onSurfaceVariant: '',
    surfaceContainerLowest: '',
    surfaceContainerLow: '',
    surfaceContainer: '',
    surfaceContainerHigh: '',
    surfaceContainerHighest: '',
    inverseSurface: '',
    inverseOnSurface: '',
    inversePrimary: '',
    outline: '',
    outlineVariant: '',
    primaryFixed: '',
    secondaryFixed: '',
    tertiaryFixed: '',
    primaryFixedDim: '',
    secondaryFixedDim: '',
    tertiaryFixedDim: '',
    onPrimaryFixed: '',
    onSecondaryFixed: '',
    onTertiaryFixed: '',
    onPrimaryFixedVariant: '',
    onSecondaryFixedVariant: '',
    onTertiaryFixedVariant: '',
    surfaceDim: '',
    surfaceBright: '',
    shadow: '',
    scrim: '',
  },
  typeFace: {
    brand: '',
    plain: '',
    weight: {
      regular: '',
      medium: '',
      bold: '',
    },
  },
  typeScale: {
    display: {
      lg: {
        family: '',
        lineHeight: '',
        size: '',
        letterSpacing: '',
        weight: '',
        weightProminent: '',
      },
      md: {
        family: '',
        lineHeight: '',
        size: '',
        letterSpacing: '',
        weight: '',
        weightProminent: '',
      },
      sm: {
        family: '',
        lineHeight: '',
        size: '',
        letterSpacing: '',
        weight: '',
        weightProminent: '',
      },
    },
    headline: {
      lg: {
        family: '',
        lineHeight: '',
        size: '',
        letterSpacing: '',
        weight: '',
        weightProminent: '',
      },
      md: {
        family: '',
        lineHeight: '',
        size: '',
        letterSpacing: '',
        weight: '',
        weightProminent: '',
      },
      sm: {
        family: '',
        lineHeight: '',
        size: '',
        letterSpacing: '',
        weight: '',
        weightProminent: '',
      },
    },
    title: {
      lg: {
        family: '',
        lineHeight: '',
        size: '',
        letterSpacing: '',
        weight: '',
        weightProminent: '',
      },
      md: {
        family: '',
        lineHeight: '',
        size: '',
        letterSpacing: '',
        weight: '',
        weightProminent: '',
      },
      sm: {
        family: '',
        lineHeight: '',
        size: '',
        letterSpacing: '',
        weight: '',
        weightProminent: '',
      },
    },
    body: {
      lg: {
        family: '',
        lineHeight: '',
        size: '',
        letterSpacing: '',
        weight: '',
        weightProminent: '',
      },
      md: {
        family: '',
        lineHeight: '',
        size: '',
        letterSpacing: '',
        weight: '',
        weightProminent: '',
      },
      sm: {
        family: '',
        lineHeight: '',
        size: '',
        letterSpacing: '',
        weight: '',
        weightProminent: '',
      },
    },
    label: {
      lg: {
        family: '',
        lineHeight: '',
        size: '',
        letterSpacing: '',
        weight: '',
        weightProminent: '',
      },
      md: {
        family: '',
        lineHeight: '',
        size: '',
        letterSpacing: '',
        weight: '',
        weightProminent: '',
      },
      sm: {
        family: '',
        lineHeight: '',
        size: '',
        letterSpacing: '',
        weight: '',
        weightProminent: '',
      },
    },
  },
  density: {
    scale: '',
    interval: '',
    minTargetSize: '',
  },
  motion: {
    easing: {
      emphasized: {
        accelerate: '',
        decelerate: '',
      },
      standard: {
        normal: '',
        accelerate: '',
        decelerate: '',
      },
      linear: '',
    },
    duration: {
      short: {
        xs: '',
        sm: '',
        md: '',
        lg: '',
      },
      medium: {
        xs: '',
        sm: '',
        md: '',
        lg: '',
      },
      long: {
        xs: '',
        sm: '',
        md: '',
        lg: '',
      },
      extraLong: {
        xs: '',
        sm: '',
        md: '',
        lg: '',
      },
    },
  },
  shape: {
    corner: {
      none: '',
      xs: '',
      sm: '',
      md: '',
      lg: '',
      xl: '',
      full: '',
      circle: '',
    },
  },
  outline: {
    width: {
      none: '',
      xs: '',
      sm: '',
      md: '',
      lg: '',
      xl: '',
    },
  },
  spacing: {
    gridSize: '',
  },
  state: {
    stateLayerOpacity: {
      hovered: '',
      pressed: '',
      dragged: '',
    },
    containerOpacity: {
      disabled: '',
    },
    opacity: {
      disabled: '',
    },
    outlineOpacity: {
      disabled: '',
    },
  },
  zIndex: {
    app: '',
    modal: '',
    popover: '',
    overlay: '',
    max: '',
  },
  elevation: {
    transitionDuration: '',
    transitionTimingFunction: '',
    level: {
      '0': {
        primary: {
          offsetX: '',
          offsetY: '',
          blurRadius: '',
          spreadRadius: '',
          colorOpacityPercentage: '',
        },
        secondary: {
          offsetX: '',
          offsetY: '',
          blurRadius: '',
          spreadRadius: '',
          colorOpacityPercentage: '',
        },
      },
      '1': {
        primary: {
          offsetX: '',
          offsetY: '',
          blurRadius: '',
          spreadRadius: '',
          colorOpacityPercentage: '',
        },
        secondary: {
          offsetX: '',
          offsetY: '',
          blurRadius: '',
          spreadRadius: '',
          colorOpacityPercentage: '',
        },
      },
      '2': {
        primary: {
          offsetX: '',
          offsetY: '',
          blurRadius: '',
          spreadRadius: '',
          colorOpacityPercentage: '',
        },
        secondary: {
          offsetX: '',
          offsetY: '',
          blurRadius: '',
          spreadRadius: '',
          colorOpacityPercentage: '',
        },
      },
      '3': {
        primary: {
          offsetX: '',
          offsetY: '',
          blurRadius: '',
          spreadRadius: '',
          colorOpacityPercentage: '',
        },
        secondary: {
          offsetX: '',
          offsetY: '',
          blurRadius: '',
          spreadRadius: '',
          colorOpacityPercentage: '',
        },
      },
      '4': {
        primary: {
          offsetX: '',
          offsetY: '',
          blurRadius: '',
          spreadRadius: '',
          colorOpacityPercentage: '',
        },
        secondary: {
          offsetX: '',
          offsetY: '',
          blurRadius: '',
          spreadRadius: '',
          colorOpacityPercentage: '',
        },
      },
      '5': {
        primary: {
          offsetX: '',
          offsetY: '',
          blurRadius: '',
          spreadRadius: '',
          colorOpacityPercentage: '',
        },
        secondary: {
          offsetX: '',
          offsetY: '',
          blurRadius: '',
          spreadRadius: '',
          colorOpacityPercentage: '',
        },
      },
    },
  },
};
