export type ITonalPalettesThemeVars = {
  black: string;
  white: string;

  // primary
  primary0: string;
  primary10: string;
  primary20: string;
  primary25: string;
  primary30: string;
  primary35: string;
  primary40: string;
  primary50: string;
  primary60: string;
  primary70: string;
  primary80: string;
  primary90: string;
  primary95: string;
  primary98: string;
  primary99: string;
  primary100: string;

  // secondary
  secondary0: string;
  secondary10: string;
  secondary20: string;
  secondary25: string;
  secondary30: string;
  secondary35: string;
  secondary40: string;
  secondary50: string;
  secondary60: string;
  secondary70: string;
  secondary80: string;
  secondary90: string;
  secondary95: string;
  secondary98: string;
  secondary99: string;
  secondary100: string;

  // tertiary
  tertiary0: string;
  tertiary10: string;
  tertiary20: string;
  tertiary25: string;
  tertiary30: string;
  tertiary35: string;
  tertiary40: string;
  tertiary50: string;
  tertiary60: string;
  tertiary70: string;
  tertiary80: string;
  tertiary90: string;
  tertiary95: string;
  tertiary98: string;
  tertiary99: string;
  tertiary100: string;

  // neutral
  neutral0: string;
  neutral4: string;
  neutral6: string;
  neutral10: string;
  neutral12: string;
  neutral17: string;
  neutral20: string;
  neutral22: string;
  neutral24: string;
  neutral25: string;
  neutral30: string;
  neutral35: string;
  neutral40: string;
  neutral50: string;
  neutral60: string;
  neutral70: string;
  neutral80: string;
  neutral87: string;
  neutral90: string;
  neutral92: string;
  neutral94: string;
  neutral95: string;
  neutral96: string;
  neutral98: string;
  neutral99: string;
  neutral100: string;

  // neutral-variant
  neutralVariant0: string;
  neutralVariant10: string;
  neutralVariant20: string;
  neutralVariant25: string;
  neutralVariant30: string;
  neutralVariant35: string;
  neutralVariant40: string;
  neutralVariant50: string;
  neutralVariant60: string;
  neutralVariant70: string;
  neutralVariant80: string;
  neutralVariant90: string;
  neutralVariant95: string;
  neutralVariant98: string;
  neutralVariant99: string;
  neutralVariant100: string;

  // error
  error0: string;
  error10: string;
  error20: string;
  error25: string;
  error30: string;
  error35: string;
  error40: string;
  error50: string;
  error60: string;
  error70: string;
  error80: string;
  error90: string;
  error95: string;
  error98: string;
  error99: string;
  error100: string;
};
