export type IRichTooltipContentStyleKey =
  | 'host'
  | 'content'
  | 'subhead'
  | 'supportingText'
  | 'actions'
  | 'cursor';

export type IRichTooltipContentStyleVarKey =
  | 'topSpace'
  | 'bottomSpace'
  | 'actionsBottomSpace'
  | 'leadingSpace'
  | 'trailingSpace'
  | 'gap'
  | 'containerShape'
  | 'containerColor'
  | 'containerElevation'
  | 'containerMaxWidth'
  | 'subheadColor'
  | 'subheadFont'
  | 'subheadSize'
  | 'subheadWeight'
  | 'subheadLineHeight'
  | 'subheadLetterSpacing'
  | 'supportingTextColor'
  | 'supportingTextFont'
  | 'supportingTextSize'
  | 'supportingTextWeight'
  | 'supportingTextLineHeight'
  | 'supportingTextLetterSpacing';
