export type IStepConnectorStyleKey =
  | 'host'
  | 'host$horizontal$rightLabel'
  | 'host$horizontal$bottomLabel'
  | 'host$vertical$rightLabel'
  | 'host$vertical$bottomLabel'
  | 'container$horizontal'
  | 'container$vertical'
  | 'container$horizontal$topText'
  | 'container$horizontal$middleText'
  | 'container$horizontal$bottomText'
  | 'line'
  | 'line$completed'
  | 'line$horizontal'
  | 'line$vertical'
  | 'line$horizontal$rightLabel$hasText'
  | 'text'
  | 'text$completed'
  | 'text$horizontal'
  | 'text$vertical';

export type IStepConnectorStyleVarKey =
  | 'thickness'
  | 'shape'
  | 'color'
  | 'color$completed'
  | 'textSpace$horizontal'
  | 'textSpace$vertical'
  | 'textColor'
  | 'textFont'
  | 'textSize'
  | 'textWeight'
  | 'textLineHeight'
  | 'textLetterSpacing'
  | 'textColor$completed';
