export type IStepConnectorStyleKey =
  | 'host'
  | 'host$horizontal'
  | 'host$vertical'
  | 'host$rightLabel'
  | 'host$bottomLabel'
  | 'line'
  | 'line$completed'
  | 'line$horizontal'
  | 'line$vertical'
  | 'line$hasContent$horizontal'
  | 'line$hasContent$vertical'
  | 'text'
  | 'text$completed'
  | 'text$horizontal'
  | 'text$vertical';

export type IStepConnectorStyleVarKey =
  | 'thickness'
  | 'shape'
  | 'color'
  | 'color$completed'
  | 'minLength$horizontal'
  | 'minLength$vertical'
  | 'textSpace$horizontal'
  | 'textSpace$vertical'
  | 'textColor'
  | 'textFont'
  | 'textSize'
  | 'textWeight'
  | 'textLineHeight'
  | 'textLetterSpacing'
  | 'textColor$completed';
