/* 🤖 this file was generated by svg-to-ts */
export const iconTriangleRight: {
  name: 'triangle_right';
  data: string;
} = {
  name: 'triangle_right',
  data: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="7 10 5 10" fill="currentColor" width="1em" height="1em"><polygon stroke="none" fill-rule="evenodd" points="12 15 7 20 7 10"/></svg>`,
};
