/* 🤖 this file was generated by svg-to-ts */
export const iconGripDotsVertical: {
  name: 'grip_dots_vertical';
  data: string;
} = {
  name: 'grip_dots_vertical',
  data: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 512" fill="currentColor" data-source="fontawesome" data-name="classic/grip-dots-vertical" width="1em" height="1em"><path d="M48 144a48 48 0 1 0 0-96 48 48 0 1 0 0 96zm0 160a48 48 0 1 0 0-96 48 48 0 1 0 0 96zM96 416A48 48 0 1 0 0 416a48 48 0 1 0 96 0zM208 144a48 48 0 1 0 0-96 48 48 0 1 0 0 96zm48 112a48 48 0 1 0 -96 0 48 48 0 1 0 96 0zM208 464a48 48 0 1 0 0-96 48 48 0 1 0 0 96z"/></svg>`,
};
