/* 🤖 this file was generated by svg-to-ts */
export const iconTriangleUp: {
  name: 'triangle_up';
  data: string;
} = {
  name: 'triangle_up',
  data: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 12 7" fill="currentColor" width="1em" height="1em"><polygon stroke="none" fill-rule="evenodd" points="1 6 6 1 11 6"/></svg>`,
};
