/* 🤖 this file was generated by svg-to-ts */
export const iconCheckmark: {
  name: 'checkmark';
  data: string;
} = {
  name: 'checkmark',
  data: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" data-source="heroicicons" data-name="solid/check" width="1em" height="1em"><path fill-rule="evenodd" d="M19.916 4.626a.75.75 0 0 1 .208 1.04l-9 13.5a.75.75 0 0 1-1.154.114l-6-6a.75.75 0 0 1 1.06-1.06l5.353 5.353 8.493-12.74a.75.75 0 0 1 1.04-.207Z" clip-rule="evenodd"/></svg>`,
};
