/* 🤖 this file was generated by svg-to-ts */
export const iconArrowDownTray: {
  name: 'arrow_down_tray';
  data: string;
} = {
  name: 'arrow_down_tray',
  data: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" data-source="heroicicons" data-name="outline/arrow-down-tray" width="1em" height="1em"><path stroke-linecap="round" stroke-linejoin="round" d="M3 16.5v2.25A2.25 2.25 0 0 0 5.25 21h13.5A2.25 2.25 0 0 0 21 18.75V16.5M16.5 12 12 16.5m0 0L7.5 12m4.5 4.5V3"/></svg>`,
};
