/* 🤖 this file was generated by svg-to-ts */
export const iconArrowUpTray: {
  name: 'arrow_up_tray';
  data: string;
} = {
  name: 'arrow_up_tray',
  data: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" data-source="heroicicons" data-name="outline/arrow-up-tray" width="1em" height="1em"><path stroke-linecap="round" stroke-linejoin="round" d="M3 16.5v2.25A2.25 2.25 0 0 0 5.25 21h13.5A2.25 2.25 0 0 0 21 18.75V16.5m-13.5-9L12 3m0 0 4.5 4.5M12 3v13.5"/></svg>`,
};
