/* 🤖 this file was generated by svg-to-ts */

export type IIcons =
  | 'checkmark'
  | 'chevron_down'
  | 'chevron_right'
  | 'chevron_up'
  | 'copy_to_cliboard'
  | 'ellipsis_horizontal'
  | 'exclamation_triangle'
  | 'eye'
  | 'eye_slash'
  | 'person'
  | 'photo'
  | 'triangle_down'
  | 'triangle_left'
  | 'triangle_right'
  | 'triangle_up'
  | 'x_mark';
export interface IIcon {
  name: IIcons;
  data: string;
}
