export type ITypographyStyleKey =
  | 'host'
  | 'host$noMargin'
  | 'display$lg'
  | 'display$md'
  | 'display$sm'
  | 'headline$lg'
  | 'headline$md'
  | 'headline$sm'
  | 'title$lg'
  | 'title$md'
  | 'title$sm'
  | 'body$lg'
  | 'body$md'
  | 'body$sm'
  | 'label$lg'
  | 'label$md'
  | 'label$sm';
