/* 🤖 this file was generated by svg-to-ts */
export * from './build/icon-AvatarPlaceholder.icon';
export * from './build/icon-CheckMark.icon';
export * from './build/icon-ChevronDown.icon';
export * from './build/icon-ChevronRight.icon';
export * from './build/icon-ChevronUp.icon';
export * from './build/icon-CopyToCliboard.icon';
export * from './build/icon-EllipsisHorizontal.icon';
export * from './build/icon-ExclamationTriangle.icon';
export * from './build/icon-Eye.icon';
export * from './build/icon-EyeSlash.icon';
export * from './build/icon-Person.icon';
export * from './build/icon-Photo.icon';
export * from './build/icon-TriangleDown.icon';
export * from './build/icon-TriangleLeft.icon';
export * from './build/icon-TriangleRight.icon';
export * from './build/icon-TriangleUp.icon';
export * from './build/icon-XMark.icon';
