export type IStepStyleKey =
  | 'host'
  | 'separator'
  | 'button'
  | 'button$horizontal'
  | 'button$vertical'
  | 'buttonFocusRing'
  | 'buttonInner'
  | 'buttonInner$hasIcon'
  | 'buttonInner$withText'
  | 'buttonInner$horizontal'
  | 'buttonInner$vertical'
  | 'stepIndex'
  | 'stepIndex$icon'
  | 'stepIndex$icon$active'
  | 'stepIndex$icon$completed'
  | 'stepIndex$icon$disabled'
  | 'stepIndex$icon$error'
  | 'stepIndex$text'
  | 'stepIndex$text$active'
  | 'stepIndex$text$completed'
  | 'stepIndex$text$disabled'
  | 'stepIndex$text$error'
  | 'labelContainer'
  | 'labelContainer$active'
  | 'labelContainer$completed'
  | 'labelContainer$disabled'
  | 'labelContainer$error'
  | 'labelContainer$horizontal'
  | 'labelContainer$vertical'
  | 'label'
  | 'supportingText';

export type IStepStyleVarKey = 'textColor';
