export type IStepStyleKey =
  | 'host'
  | 'host$rightLabel'
  | 'host$bottomLabel'
  | 'separator'
  | 'button'
  | 'button$rightLabel'
  | 'button$bottomLabel'
  | 'buttonFocusRing'
  | 'buttonInner'
  | 'buttonInner$hasIcon'
  | 'buttonInner$withText'
  | 'buttonInner$rightLabel'
  | 'buttonInner$bottomLabel'
  | 'stepIndex'
  | 'stepIndex$icon'
  | 'stepIndex$icon$active'
  | 'stepIndex$icon$completed'
  | 'stepIndex$icon$disabled'
  | 'stepIndex$icon$error'
  | 'stepIndex$text'
  | 'stepIndex$text$active'
  | 'stepIndex$text$completed'
  | 'stepIndex$text$disabled'
  | 'stepIndex$text$error'
  | 'labelContainer'
  | 'labelContainer$active'
  | 'labelContainer$completed'
  | 'labelContainer$disabled'
  | 'labelContainer$error'
  | 'labelContainer$rightLabel'
  | 'labelContainer$bottomLabel'
  | 'label'
  | 'supportingText'
  | 'content';

export type IStepStyleVarKey = 'textColor';
