name: Publish

on:
  push:
    branches:
      - main
    tags:
      - v*.*.*

jobs:
  test:
    name: Publish
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        node-version: [22]
    permissions:
      contents: read
      id-token: write
    if: ${{ !contains(github.event.head_commit.message, 'skip ci') }}
    steps:
      - uses: actions/checkout@v4
        with:
          # Fetches all history so Chromatic can compare against previous
          # builds.
          fetch-depth: 0
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.4.1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Print Environment Info
        run: npx nx report
        shell: bash
      - name: Release packages
        run: npx nx release --skip-publish
        shell: bash
      - name: Publish packages
        run: npx nx release publish
        shell: bash
        env:
          NPM_CONFIG_PROVENANCE: true
